# Generated by Django 4.2.16 on 2026-05-26 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='source_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='upload_batches', to='ingestion.sourcesystem'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='unitconversion',
            unique_together={('from_unit', 'to_unit')},
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='source_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_records', to='ingestion.sourcesystem'),
        ),
        migrations.AddField(
            model_name='rawrecord',
            name='upload_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.uploadbatch'),
        ),
        migrations.AddField(
            model_name='plantlookup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='emission_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ingestion.emissioncategory'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_record', to='ingestion.rawrecord'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='source_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_records', to='ingestion.sourcesystem'),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='upload_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingestion.uploadbatch'),
        ),
        migrations.AddField(
            model_name='anomalyflag',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='ingestion.normalizedrecord'),
        ),
        migrations.AlterUniqueTogether(
            name='rawrecord',
            unique_together={('upload_batch', 'row_number')},
        ),
        migrations.AlterUniqueTogether(
            name='plantlookup',
            unique_together={('organization', 'plant_code')},
        ),
    ]
