version: '3.9'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: breathe_esg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_reference_data &&
             python manage.py seed_demo &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/breathe_esg
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DEBUG: 'False'
      ALLOWED_HOSTS: '*'
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    command: celery -A config worker -l info
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/breathe_esg
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      DEBUG: 'False'
      ALLOWED_HOSTS: '*'
    depends_on:
      - backend
      - redis

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - '5173:80'
    depends_on:
      - backend

volumes:
  db_data:
